import type { BlueWhaleStore, BusinessOffer, CreatorApplication, CreatorOfferPreference, OperatorTask } from './types'

const now = '2026-04-30T00:00:00.000Z'

const offer = (item: Omit<BusinessOffer, 'status' | 'created_at' | 'updated_at'>): BusinessOffer => ({
  ...item,
  status: 'active',
  created_at: now,
  updated_at: now,
})

const creator = (item: Omit<CreatorApplication, 'status' | 'created_at' | 'updated_at'>): CreatorApplication => ({
  ...item,
  status: 'blue_whale_reviewing',
  created_at: now,
  updated_at: now,
})

const preference = (item: Omit<CreatorOfferPreference, 'created_at' | 'updated_at'>): CreatorOfferPreference => ({
  ...item,
  created_at: now,
  updated_at: now,
})

const task = (item: Omit<OperatorTask, 'created_at' | 'updated_at'>): OperatorTask => ({
  ...item,
  created_at: now,
  updated_at: now,
})

export const seedStore: BlueWhaleStore = {
  business_offers: [
    offer({
      id: 'offer-jeju-orcar',
      login_id: 'jeju-car',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Rental Car',
      sponsorship_details: '48-hour contactless rental car support, insurance included, fuel excluded',
      desired_content_types: ['Instagram Reel', 'TikTok'],
      no_content_preference: false,
      business_name: 'Orcar-style Jeju Contactless Rental',
      image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Orcar rental operations',
      reference_url: 'https://orcar.ai/en',
      source_type: 'reference',
      availability_status: 'partner_confirmed',
      address: 'Jeju International Airport pickup zone',
      website_or_social: 'https://orcar.ai/en',
      short_description: 'A mobility offer for creators filming flexible Jeju routes without counter pickup friction.',
      contact_email: 'partners@orcar.example',
    }),
    offer({
      id: 'offer-jeju-seogwipo-stay',
      login_id: 'seogwipo-stay',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Hotel',
      sponsorship_details: '1-night ocean-view stay, breakfast included, weekday preferred',
      desired_content_types: ['Instagram Reel', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Seogwipo Ocean Stay',
      image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Seeded stay example',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Seogwipo coastal road',
      short_description: 'A calm coastal stay for creators making room tours, sunrise clips, and itinerary posts.',
      contact_phone: '010-0000-1101',
    }),
    offer({
      id: 'offer-jeju-aewol-villa',
      login_id: 'aewol-villa',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Hotel',
      sponsorship_details: '1-night private pool villa stay, weekdays only during the MVP',
      desired_content_types: ['Instagram Reel', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Aewol Cliff Pool Villa',
      image_url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Seeded villa example',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Aewol coastal village',
      short_description: 'A photogenic villa concept for creators who can show the stay as part of a Jeju route.',
      contact_email: 'host@aewolvilla.example',
    }),
    offer({
      id: 'offer-jeju-forest-cabin',
      login_id: 'forest-cabin',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Hotel',
      sponsorship_details: '1-night forest cabin stay, self check-in, weekday dates to be reviewed',
      desired_content_types: ['Blog Post', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Jeju Forest Cabin Stay',
      image_url: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Seeded boutique stay example',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Jeju mid-mountain forest road',
      short_description: 'A quiet stay suited to slower review posts and nature-focused travel diaries.',
      contact_email: 'hello@forestcabin.example',
    }),
    offer({
      id: 'offer-jeju-gogi-guksu',
      login_id: 'gogi-guksu',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Restaurant',
      sponsorship_details: 'Gogi-guksu meal for 2, signature pork noodle menu included',
      desired_content_types: ['Instagram Reel', 'Blog Post'],
      no_content_preference: false,
      business_name: 'Mukdol-inspired Jeju Gogi-guksu Table',
      image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jeju_gogi_noodle.jpg?width=1200',
      reference_label: 'Catchtable-inspired offer · image: Narnars0 / CC BY-SA 3.0',
      reference_url: 'https://app.catchtable.co.kr/ct/shop/mukdol',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Jeju local dining street',
      short_description: 'A local pork noodle visit for creators covering Jeju food routes.',
      contact_email: 'table@gogiguksu.example',
    }),
    offer({
      id: 'offer-jeju-aewol-cafe',
      login_id: 'aewol-cafe',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Cafe',
      sponsorship_details: 'Cafe set for 2, signature drinks and dessert included',
      desired_content_types: [],
      no_content_preference: true,
      business_name: 'Aewol Seaside Cafe',
      image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Aewol seaside street',
      website_or_social: 'https://instagram.com/aewol-seaside-cafe',
      short_description: 'A bright seaside cafe for casual itinerary content and short-form visuals.',
      contact_instagram: '@aewolcafe',
    }),
    offer({
      id: 'offer-jeju-udo-ebike',
      login_id: 'udo-ebike',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Activity',
      sponsorship_details: 'Udo e-bike experience pass for 2, reservation required',
      desired_content_types: ['YouTube Shorts', 'TikTok'],
      no_content_preference: false,
      business_name: 'Udo E-bike Island Route',
      image_url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Udo ferry terminal',
      short_description: 'A day-trip activity offer for creators making scenic island route content.',
      contact_email: 'hello@udobike.example',
    }),
    offer({
      id: 'offer-jeju-hallasan-photo',
      login_id: 'hallasan-photo',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Photo Shoot',
      sponsorship_details: '30-minute outdoor shoot, 10 edited photos included',
      desired_content_types: ['Photo Set', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Hallasan Travel Photo Shoot',
      image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Hallasan trail meeting point',
      short_description: 'Creator-friendly outdoor portraits around Hallasan and nearby nature spots.',
      contact_phone: '010-0000-1107',
    }),
    offer({
      id: 'offer-jeju-beauty',
      login_id: 'jeju-beauty',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Beauty',
      sponsorship_details: '1 beauty studio service, appointment time reviewed by Blue Whale',
      desired_content_types: ['Instagram Reel', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Jeju Beauty Studio',
      image_url: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Jeju City salon district',
      short_description: 'A K-beauty style studio visit for creators adding beauty to a Jeju itinerary.',
      contact_email: 'booking@jejubeauty.example',
    }),
    offer({
      id: 'offer-jeju-esim',
      login_id: 'jeju-esim',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Connectivity',
      sponsorship_details: '5-day Korea travel eSIM, setup guide included',
      desired_content_types: ['Instagram Story', 'TikTok'],
      no_content_preference: false,
      business_name: 'Superalink-inspired Jeju eSIM Pack',
      image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Superalink eSIM',
      reference_url: 'https://superalink.com/en/',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Digital delivery before arrival',
      short_description: 'A connectivity pack for creators who need data from airport arrival to upload.',
      contact_email: 'partners@esim.example',
    }),
    offer({
      id: 'offer-seoul-orcar',
      login_id: 'seoul-car',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Rental Car',
      sponsorship_details: '24-hour contactless rental car support, fuel excluded',
      desired_content_types: ['Instagram Reel', 'TikTok'],
      no_content_preference: false,
      business_name: 'Orcar-style Seoul Contactless Rental',
      image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Orcar rental operations',
      reference_url: 'https://orcar.ai/en',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Gangnam and Hongdae pickup zones',
      short_description: 'A city mobility offer for creators filming multiple Seoul neighborhoods.',
      contact_email: 'seoul@orcar.example',
    }),
    offer({
      id: 'offer-seoul-bukchon',
      login_id: 'bukchon-stay',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Hotel',
      sponsorship_details: '1-night boutique stay near Bukchon, weekday preferred',
      desired_content_types: ['Instagram Reel', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Bukchon Courtyard Stay',
      image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Bukchon, Seoul',
      short_description: 'A quiet heritage-area stay for creators covering Seoul streets and design shops.',
      contact_email: 'stay@bukchon.example',
    }),
    offer({
      id: 'offer-seoul-hongdae',
      login_id: 'hongdae-hotel',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Hotel',
      sponsorship_details: '1-night creator room, late checkout included',
      desired_content_types: ['YouTube Shorts', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Hongdae Creator Hotel',
      image_url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Hongdae, Seoul',
      short_description: 'An urban stay close to nightlife, cafes, pop-ups, and street content routes.',
      contact_email: 'hello@hongdaehotel.example',
    }),
    offer({
      id: 'offer-seoul-beauty',
      login_id: 'seongsu-skin',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Beauty',
      sponsorship_details: '1 skin consultation or treatment, appointment time to be reviewed',
      desired_content_types: ['Instagram Reel', 'Blog Post'],
      no_content_preference: false,
      business_name: 'iipuda-inspired Seongsu K-beauty Clinic',
      image_url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by iipuda K-beauty',
      reference_url: 'https://iipuda.com/en/',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Seongsu, Seoul',
      short_description: 'A K-beauty clinic visit for creators making Seoul beauty itinerary content.',
      contact_email: 'partner@seongsuskin.example',
    }),
    offer({
      id: 'offer-seoul-esim',
      login_id: 'seoul-esim',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Connectivity',
      sponsorship_details: '7-day Korea eSIM data plan, instant QR activation',
      desired_content_types: ['Instagram Story', 'TikTok'],
      no_content_preference: false,
      business_name: 'Superalink-inspired Seoul eSIM Pack',
      image_url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Superalink eSIM',
      reference_url: 'https://superalink.com/en/',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Digital delivery before arrival',
      short_description: 'A travel data offer for creators arriving in Seoul and uploading on the move.',
      contact_email: 'seoul@esim.example',
    }),
    offer({
      id: 'offer-busan-orcar',
      login_id: 'busan-car',
      password: 'demo1234',
      location: 'Busan',
      category: 'Rental Car',
      sponsorship_details: '24-hour rental car, pickup near Busan Station, fuel excluded',
      desired_content_types: ['Instagram Reel', 'YouTube Shorts'],
      no_content_preference: false,
      business_name: 'Orcar-style Busan Coastal Rental',
      image_url: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Orcar rental operations',
      reference_url: 'https://orcar.ai/en',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Busan Station pickup zone',
      short_description: 'A coastal driving package for Haeundae, Gwangalli, and Yeongdo routes.',
      contact_email: 'busan@orcar.example',
    }),
    offer({
      id: 'offer-busan-haeundae',
      login_id: 'haeundae-hotel',
      password: 'demo1234',
      location: 'Busan',
      category: 'Hotel',
      sponsorship_details: '1-night ocean-view room, weekday preferred',
      desired_content_types: ['Instagram Reel', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Haeundae Ocean-view Stay',
      image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Haeundae Beach, Busan',
      short_description: 'A beachfront stay for sunrise reels, room tours, and Busan weekend guides.',
      contact_email: 'stay@haeundae.example',
    }),
    offer({
      id: 'offer-busan-gwangalli',
      login_id: 'gwangalli-stay',
      password: 'demo1234',
      location: 'Busan',
      category: 'Hotel',
      sponsorship_details: '1-night stay near Gwangalli, rooftop access included',
      desired_content_types: ['Instagram Reel', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Gwangalli Sunset Stay',
      image_url: 'https://images.unsplash.com/photo-1444201983204-c43cbd584d93?auto=format&fit=crop&w=1200&q=80',
      source_type: 'seeded',
      availability_status: 'requestable',
      address: 'Gwangalli, Busan',
      short_description: 'A sunset-focused stay for creators filming the beach, bridge, and night view.',
      contact_email: 'hello@gwangalli.example',
    }),
    offer({
      id: 'offer-busan-beauty',
      login_id: 'suyeong-beauty',
      password: 'demo1234',
      location: 'Busan',
      category: 'Beauty',
      sponsorship_details: '1 beauty consultation or skin service near Suyeong Station',
      desired_content_types: ['Instagram Reel', 'Blog Post'],
      no_content_preference: false,
      business_name: 'iipuda-inspired Busan K-beauty Clinic',
      image_url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by iipuda Busan clinic listings',
      reference_url: 'https://iipuda.com/en/',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Suyeong Station, Busan',
      short_description: 'A Busan beauty clinic option for creators covering K-beauty outside Seoul.',
      contact_email: 'partners@suyeongbeauty.example',
    }),
    offer({
      id: 'offer-busan-esim',
      login_id: 'busan-esim',
      password: 'demo1234',
      location: 'Busan',
      category: 'Connectivity',
      sponsorship_details: '5-day Korea eSIM data plan, hotspot allowed',
      desired_content_types: ['Instagram Story', 'YouTube Shorts'],
      no_content_preference: false,
      business_name: 'Superalink-inspired Busan eSIM Pack',
      image_url: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Superalink eSIM',
      reference_url: 'https://superalink.com/en/',
      source_type: 'reference',
      availability_status: 'requestable',
      address: 'Digital delivery before arrival',
      short_description: 'A mobile data sponsorship for creators uploading Busan travel content throughout the trip.',
      contact_email: 'busan@esim.example',
    }),
  ],
  creator_applications: [
    creator({
      id: 'creator-ari-reels',
      nickname: 'ari-reels',
      password: 'demo1234',
      destination: 'Jeju',
      start_date: '2026-05-18',
      end_date: '2026-05-22',
      contact_instagram: '@ari.travels',
      contact_email: 'ari@example.com',
    }),
    creator({
      id: 'creator-family-shorts',
      nickname: 'family-shorts',
      password: 'demo1234',
      destination: 'Jeju',
      start_date: '2026-06-03',
      end_date: '2026-06-07',
      contact_email: 'family@example.com',
      contact_phone: 'Kakao: familytrip',
    }),
    creator({
      id: 'creator-jeju-blogger',
      nickname: 'jeju-blogger',
      password: 'demo1234',
      destination: 'Jeju',
      start_date: '2026-05-28',
      end_date: '2026-05-31',
      contact_email: 'reviewer@example.com',
    }),
  ],
  creator_social_accounts: [
    {
      id: 'social-ari-instagram',
      creator_application_id: 'creator-ari-reels',
      platform: 'Instagram',
      handle: 'ari.travels',
      profile_url: 'https://instagram.com/ari.travels',
      reviewed_followers: 48300,
      reviewed_average_views: 21400,
      reviewed_average_likes: 1700,
      created_at: now,
    },
    {
      id: 'social-family-youtube',
      creator_application_id: 'creator-family-shorts',
      platform: 'YouTube',
      handle: 'familytravelshorts',
      profile_url: 'https://youtube.com/@familytravelshorts',
      reviewed_followers: 12800,
      reviewed_average_views: 9400,
      created_at: now,
    },
    {
      id: 'social-blogger-naver',
      creator_application_id: 'creator-jeju-blogger',
      platform: 'Naver Blog',
      handle: 'jeju-review-log',
      profile_url: 'https://blog.naver.com/jeju-review-log',
      reviewed_average_views: 5200,
      created_at: now,
    },
  ],
  creator_offer_preferences: [
    preference({
      id: 'pref-ari-car',
      creator_application_id: 'creator-ari-reels',
      business_offer_id: 'offer-jeju-orcar',
      preference: 'interested',
      outreach_status: 'business_contacted',
      operator_notes: 'Good fit for airport pickup content. Contacted car team.',
    }),
    preference({
      id: 'pref-ari-stay',
      creator_application_id: 'creator-ari-reels',
      business_offer_id: 'offer-jeju-seogwipo-stay',
      preference: 'interested',
      outreach_status: 'blue_whale_reviewing',
      operator_notes: 'Need to verify weekday availability.',
    }),
    preference({
      id: 'pref-family-ebike',
      creator_application_id: 'creator-family-shorts',
      business_offer_id: 'offer-jeju-udo-ebike',
      preference: 'interested',
      outreach_status: 'interest_saved',
    }),
    preference({
      id: 'pref-family-car',
      creator_application_id: 'creator-family-shorts',
      business_offer_id: 'offer-jeju-orcar',
      preference: 'interested',
      outreach_status: 'proposal_received',
      operator_notes: 'Proposal entered for 48-hour compact SUV.',
    }),
    preference({
      id: 'pref-blogger-gogi',
      creator_application_id: 'creator-jeju-blogger',
      business_offer_id: 'offer-jeju-gogi-guksu',
      preference: 'interested',
      outreach_status: 'business_replied',
      operator_notes: 'Restaurant asked for weekday lunch window.',
    }),
  ],
  business_proposals: [
    {
      id: 'proposal-car-family',
      business_offer_id: 'offer-jeju-orcar',
      creator_application_id: 'creator-family-shorts',
      title: 'Family rental car support',
      provide_details: '48-hour compact SUV rental with standard insurance included.',
      proposal_message: 'Blue Whale reviewed your trip and the business is open to supporting your Jeju family route.',
      included_items: 'Vehicle rental, standard insurance, child seat if available',
      excluded_items: 'Fuel, parking, toll fees',
      requested_content: '1 YouTube Shorts and 1 Instagram Story',
      available_dates: 'June 3-7, 2026',
      upload_deadline: 'Within 10 days after visit',
      contact_preference: 'blue_whale',
      status: 'proposal_received',
      created_at: now,
      updated_at: now,
    },
  ],
  operator_tasks: [
    task({
      id: 'task-ari-car',
      type: 'contact_business',
      creator_application_id: 'creator-ari-reels',
      business_offer_id: 'offer-jeju-orcar',
      status: 'in_progress',
      notes: 'Contacted car team; waiting for date confirmation.',
    }),
    task({
      id: 'task-family-proposal',
      type: 'deliver_proposal',
      creator_application_id: 'creator-family-shorts',
      business_offer_id: 'offer-jeju-orcar',
      business_proposal_id: 'proposal-car-family',
      status: 'open',
      notes: 'Proposal visible to returning creator.',
    }),
    task({
      id: 'task-blogger-gogi',
      type: 'contact_business',
      creator_application_id: 'creator-jeju-blogger',
      business_offer_id: 'offer-jeju-gogi-guksu',
      status: 'in_progress',
      notes: 'Restaurant replied; operator should create a proposal after confirming lunch date.',
    }),
  ],
}
