import type { BlueWhaleStore } from './types'

const now = '2026-04-30T00:00:00.000Z'

export const seedStore: BlueWhaleStore = {
  business_offers: [
    {
      id: 'offer-jeju-rental-car',
      login_id: 'jeju-car',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Rental Car',
      sponsorship_details: '48-hour rental car, insurance included, fuel excluded',
      desired_content_types: ['Instagram Reel', 'TikTok'],
      no_content_preference: false,
      business_name: 'Jeju Airport Rental Car',
      image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Orcar car rental',
      reference_url: 'https://orcar.ai/en',
      address: 'Jeju International Airport pickup zone',
      website_or_social: 'https://orcar.ai/en',
      short_description: 'Contactless rental support for creators filming flexible Jeju itineraries.',
      contact_name: 'Mina Park',
      contact_email: 'partner@jejuairportcar.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-seogwipo-stay',
      login_id: 'ocean-stay',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Hotel',
      sponsorship_details: '1-night ocean view stay, breakfast included, weekends excluded',
      desired_content_types: ['Instagram Reel', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Seogwipo Ocean View Stay',
      image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Hotel-style stay example',
      reference_url: 'https://finestays.com/search',
      address: 'Seogwipo coastal road',
      website_or_social: 'https://finestays.com/search',
      short_description: 'A quiet ocean-view stay near Seogwipo for relaxed travel content.',
      contact_name: 'Jun Lee',
      contact_phone: '010-0000-1002',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-aewol-cliff-villa',
      login_id: 'aewol-villa',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Hotel',
      sponsorship_details: '1-night pool villa stay, weekday check-in preferred',
      desired_content_types: ['Instagram Reel', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Aewol Cliff Pool Villa',
      image_url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Fine stay listing style',
      reference_url: 'https://finestays.com/search',
      address: 'Aewol coastal village',
      website_or_social: 'https://finestays.com/search',
      short_description: 'Private villa stay with a photogenic pool deck and sunset coastline mood.',
      contact_email: 'host@aewolcliff.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-jeju-forest-stay',
      login_id: 'forest-stay',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Hotel',
      sponsorship_details: '1-night forest cabin stay, self check-in available',
      desired_content_types: ['Blog Post', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Jeju Forest Private Stay',
      image_url: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Boutique stay concept',
      reference_url: 'https://finestays.com/search',
      address: 'Jeju mid-mountain forest road',
      website_or_social: 'https://finestays.com/search',
      short_description: 'A calm forest hideaway for itinerary videos, review posts, and slow travel photos.',
      contact_email: 'hello@jejuforeststay.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-udo-ebike',
      login_id: 'udo-ebike',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Activity',
      sponsorship_details: 'Experience pass for 2, reservation required',
      desired_content_types: ['YouTube Shorts', 'TikTok'],
      no_content_preference: false,
      business_name: 'Udo E-bike Tour',
      image_url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80',
      address: 'Udo ferry terminal',
      website_or_social: 'https://example.com/udo-ebike',
      short_description: 'Scenic e-bike rentals for creators covering Udo day trips.',
      contact_email: 'hello@udobike.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-aewol-cafe',
      login_id: 'aewol-cafe',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Cafe',
      sponsorship_details: 'Cafe set for 2, signature drinks included',
      desired_content_types: [],
      no_content_preference: true,
      business_name: 'Aewol Brunch Cafe',
      image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
      address: 'Aewol seaside street',
      website_or_social: 'https://instagram.com/aewol-brunch-cafe',
      short_description: 'A bright seaside brunch cafe with photogenic drinks and pastries.',
      contact_instagram: '@aewolbrunch',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-hallasan-photo',
      login_id: 'halla-photo',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Photo Shoot',
      sponsorship_details: '30-minute photo shoot, 10 edited photos included',
      desired_content_types: ['Photo Set', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Hallasan Photo Shoot',
      image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      address: 'Hallasan trail meeting point',
      website_or_social: 'https://example.com/hallasan-photo',
      short_description: 'Outdoor photo sessions around Hallasan and nearby nature spots.',
      contact_phone: '010-0000-1005',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-jeju-beauty',
      login_id: 'jeju-beauty',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Beauty',
      sponsorship_details: '1 beauty treatment or service, appointment time to be discussed',
      desired_content_types: ['Instagram Reel', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Jeju Beauty Studio',
      image_url: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=1200&q=80',
      address: 'Jeju City salon district',
      website_or_social: 'https://instagram.com/jeju-beauty-studio',
      short_description: 'Creator-friendly beauty services near central Jeju City.',
      contact_email: 'booking@jejubeauty.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-jeju-mukdol-dinner',
      login_id: 'mukdol-jeju',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Restaurant',
      sponsorship_details: 'Gogi-guksu meal for 2, signature pork noodle menu included',
      desired_content_types: ['Instagram Reel', 'Blog Post'],
      no_content_preference: false,
      business_name: 'Mukdol Jeju Dinner Table',
      image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jeju_gogi_noodle.jpg?width=1200',
      reference_label: 'Catchtable page example · gogi-guksu image: Narnars0 / CC BY-SA 3.0',
      reference_url: 'https://app.catchtable.co.kr/ct/shop/mukdol',
      address: 'Jeju local dining street',
      website_or_social: 'https://app.catchtable.co.kr/ct/shop/mukdol',
      short_description: 'A Jeju pork noodle spot suited for creators making local food review content.',
      contact_email: 'table@mukdol.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-jeju-esim',
      login_id: 'jeju-esim',
      password: 'demo1234',
      location: 'Jeju',
      category: 'Connectivity',
      sponsorship_details: '5-day Korea travel eSIM, setup guide included',
      desired_content_types: ['Instagram Story', 'TikTok'],
      no_content_preference: false,
      business_name: 'Jeju Travel eSIM Pack',
      image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Superalink eSIM',
      reference_url: 'https://superalink.com/en/',
      address: 'Digital delivery before arrival',
      website_or_social: 'https://superalink.com/en/',
      short_description: 'A connectivity sponsorship for creators who need data from airport arrival to content upload.',
      contact_email: 'partners@traveldatamock.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-seoul-rental-car',
      login_id: 'seoul-car',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Rental Car',
      sponsorship_details: '24-hour contactless rental car, insurance included, fuel excluded',
      desired_content_types: ['Instagram Reel', 'TikTok'],
      no_content_preference: false,
      business_name: 'Seoul Contactless Rental Car',
      image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Orcar car rental',
      reference_url: 'https://orcar.ai/en',
      address: 'Gangnam and Hongdae pickup zones',
      website_or_social: 'https://orcar.ai/en',
      short_description: 'A city mobility offer for creators filming multiple Seoul neighborhoods in one day.',
      contact_email: 'seoul@contactlesscar.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-bukchon-courtyard',
      login_id: 'bukchon-stay',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Hotel',
      sponsorship_details: '1-night boutique stay near Bukchon, weekday preferred',
      desired_content_types: ['Instagram Reel', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Bukchon Courtyard Hotel',
      image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Boutique hotel market example',
      reference_url: 'https://finestays.com/search',
      address: 'Bukchon, Seoul',
      website_or_social: 'https://finestays.com/search',
      short_description: 'A quiet courtyard stay for creators covering heritage streets and design shops.',
      contact_email: 'stay@bukchoncourtyard.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-hongdae-creator-hotel',
      login_id: 'hongdae-hotel',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Hotel',
      sponsorship_details: '1-night creator room, late checkout included',
      desired_content_types: ['YouTube Shorts', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Hongdae Creator Hotel',
      image_url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Urban stay example',
      reference_url: 'https://finestays.com/search',
      address: 'Hongdae, Seoul',
      website_or_social: 'https://finestays.com/search',
      short_description: 'An urban stay close to nightlife, cafes, pop-ups, and street content routes.',
      contact_email: 'hello@hongdaecreatorhotel.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-seongsu-skin',
      login_id: 'seongsu-skin',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Beauty',
      sponsorship_details: '1 skin consultation or treatment, appointment time to be discussed',
      desired_content_types: ['Instagram Reel', 'Blog Post'],
      no_content_preference: false,
      business_name: 'Seongsu Skin Clinic Visit',
      image_url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by iipuda K-beauty',
      reference_url: 'https://iipuda.com/en/',
      address: 'Seongsu, Seoul',
      website_or_social: 'https://iipuda.com/en/',
      short_description: 'A K-beauty clinic visit for creators making Seoul beauty itinerary content.',
      contact_email: 'partner@seongsuskin.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-seoul-esim',
      login_id: 'seoul-esim',
      password: 'demo1234',
      location: 'Seoul',
      category: 'Connectivity',
      sponsorship_details: '7-day Korea eSIM data plan, instant QR activation',
      desired_content_types: ['Instagram Story', 'TikTok'],
      no_content_preference: false,
      business_name: 'Seoul Travel eSIM Pack',
      image_url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Superalink eSIM',
      reference_url: 'https://superalink.com/en/',
      address: 'Digital delivery before arrival',
      website_or_social: 'https://superalink.com/en/',
      short_description: 'A travel data offer for creators arriving in Seoul and uploading on the move.',
      contact_email: 'seoul@traveldatamock.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-busan-rental-car',
      login_id: 'busan-car',
      password: 'demo1234',
      location: 'Busan',
      category: 'Rental Car',
      sponsorship_details: '24-hour rental car, pickup near Busan Station, fuel excluded',
      desired_content_types: ['Instagram Reel', 'YouTube Shorts'],
      no_content_preference: false,
      business_name: 'Busan Coastal Rental Car',
      image_url: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Orcar car rental',
      reference_url: 'https://orcar.ai/en',
      address: 'Busan Station pickup zone',
      website_or_social: 'https://orcar.ai/en',
      short_description: 'A coastal driving support package for Haeundae, Gwangalli, and Yeongdo routes.',
      contact_email: 'busan@coastalcar.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-haeundae-ocean',
      login_id: 'haeundae-hotel',
      password: 'demo1234',
      location: 'Busan',
      category: 'Hotel',
      sponsorship_details: '1-night ocean-view room, weekday preferred',
      desired_content_types: ['Instagram Reel', 'Photo Set'],
      no_content_preference: false,
      business_name: 'Haeundae Ocean Hotel',
      image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Ocean hotel market example',
      reference_url: 'https://finestays.com/search',
      address: 'Haeundae Beach, Busan',
      website_or_social: 'https://finestays.com/search',
      short_description: 'A beachfront stay designed for sunrise reels, room tours, and Busan weekend guides.',
      contact_email: 'stay@haeundaeocean.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-gwangalli-sunset',
      login_id: 'gwangalli-stay',
      password: 'demo1234',
      location: 'Busan',
      category: 'Hotel',
      sponsorship_details: '1-night stay near Gwangalli, rooftop access included',
      desired_content_types: ['Instagram Reel', 'Instagram Story'],
      no_content_preference: false,
      business_name: 'Gwangalli Sunset Stay',
      image_url: 'https://images.unsplash.com/photo-1444201983204-c43cbd584d93?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Boutique stay example',
      reference_url: 'https://finestays.com/search',
      address: 'Gwangalli, Busan',
      website_or_social: 'https://finestays.com/search',
      short_description: 'A sunset-focused stay for creators filming the beach, bridge, and night view.',
      contact_email: 'hello@gwangallisunset.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-suyeong-beauty',
      login_id: 'suyeong-beauty',
      password: 'demo1234',
      location: 'Busan',
      category: 'Beauty',
      sponsorship_details: '1 beauty consultation or skin service near Suyeong Station',
      desired_content_types: ['Instagram Reel', 'Blog Post'],
      no_content_preference: false,
      business_name: 'Suyeong K-Beauty Clinic',
      image_url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by iipuda Busan clinic listings',
      reference_url: 'https://iipuda.com/en/',
      address: 'Suyeong Station, Busan',
      website_or_social: 'https://iipuda.com/en/',
      short_description: 'A Busan beauty clinic option for creators covering K-beauty outside Seoul.',
      contact_email: 'partners@suyeongbeauty.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'offer-busan-esim',
      login_id: 'busan-esim',
      password: 'demo1234',
      location: 'Busan',
      category: 'Connectivity',
      sponsorship_details: '5-day Korea eSIM data plan, hotspot allowed',
      desired_content_types: ['Instagram Story', 'YouTube Shorts'],
      no_content_preference: false,
      business_name: 'Busan Travel eSIM Pack',
      image_url: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=1200&q=80',
      reference_label: 'Inspired by Superalink eSIM',
      reference_url: 'https://superalink.com/en/',
      address: 'Digital delivery before arrival',
      website_or_social: 'https://superalink.com/en/',
      short_description: 'A mobile data sponsorship for creators uploading Busan travel content throughout the trip.',
      contact_email: 'busan@traveldatamock.example',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
  ],
  creator_applications: [
    {
      id: 'creator-ari-reels',
      nickname: 'ari-reels',
      password: 'demo1234',
      destination: 'Jeju',
      start_date: '2026-05-18',
      end_date: '2026-05-22',
      categories: ['Hotel', 'Rental Car', 'Cafe', 'Photo Shoot'],
      contact_instagram: '@ari.travels',
      contact_email: 'ari@example.com',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'creator-family-shorts',
      nickname: 'family-shorts',
      password: 'demo1234',
      destination: 'Jeju',
      start_date: '2026-06-03',
      end_date: '2026-06-07',
      categories: ['Rental Car', 'Activity', 'Restaurant', 'Cafe'],
      contact_email: 'family@example.com',
      contact_phone: 'Kakao: familytrip',
      status: 'Sent to Creator',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'creator-jeju-blogger',
      nickname: 'jeju-blogger',
      password: 'demo1234',
      destination: 'Jeju',
      start_date: '2026-05-28',
      end_date: '2026-05-31',
      categories: ['Beauty', 'Restaurant', 'Shopping', 'Cafe'],
      contact_email: 'reviewer@example.com',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
  ],
  creator_social_accounts: [
    {
      id: 'social-ari-instagram',
      creator_application_id: 'creator-ari-reels',
      platform: 'Instagram',
      handle: 'ari.travels',
      profile_url: 'https://instagram.com/ari.travels',
      reviewed_followers: 48300,
      reviewed_average_views: 21400,
      reviewed_average_likes: 1700,
      created_at: now,
    },
    {
      id: 'social-family-youtube',
      creator_application_id: 'creator-family-shorts',
      platform: 'YouTube',
      handle: 'familytravelshorts',
      profile_url: 'https://youtube.com/@familytravelshorts',
      reviewed_followers: 12800,
      reviewed_average_views: 9400,
      created_at: now,
    },
    {
      id: 'social-blogger-naver',
      creator_application_id: 'creator-jeju-blogger',
      platform: 'Naver Blog',
      handle: 'jeju-review-log',
      profile_url: 'https://blog.naver.com/jeju-review-log',
      reviewed_average_views: 5200,
      created_at: now,
    },
  ],
  creator_offer_preferences: [
    {
      id: 'pref-ari-car',
      creator_application_id: 'creator-ari-reels',
      business_offer_id: 'offer-jeju-rental-car',
      preference: 'interested',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'pref-ari-stay',
      creator_application_id: 'creator-ari-reels',
      business_offer_id: 'offer-seogwipo-stay',
      preference: 'interested',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'pref-ari-cafe',
      creator_application_id: 'creator-ari-reels',
      business_offer_id: 'offer-aewol-cafe',
      preference: 'not_interested',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'pref-family-ebike',
      creator_application_id: 'creator-family-shorts',
      business_offer_id: 'offer-udo-ebike',
      preference: 'interested',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'pref-family-car',
      creator_application_id: 'creator-family-shorts',
      business_offer_id: 'offer-jeju-rental-car',
      preference: 'interested',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'pref-blogger-beauty',
      creator_application_id: 'creator-jeju-blogger',
      business_offer_id: 'offer-jeju-beauty',
      preference: 'interested',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'pref-blogger-cafe',
      creator_application_id: 'creator-jeju-blogger',
      business_offer_id: 'offer-aewol-cafe',
      preference: 'interested',
      created_at: now,
      updated_at: now,
    },
  ],
  business_proposals: [
    {
      id: 'proposal-car-family',
      business_offer_id: 'offer-jeju-rental-car',
      creator_application_id: 'creator-family-shorts',
      title: 'Family rental car support',
      provide_details: '48-hour compact SUV rental with insurance included.',
      proposal_message: 'We think your family Shorts format fits our Jeju airport pickup story well.',
      included_items: 'Vehicle rental, standard insurance, child seat if available',
      excluded_items: 'Fuel, parking, toll fees',
      requested_content: '1 YouTube Shorts and 1 Instagram Story',
      available_dates: 'June 3-7, 2026',
      upload_deadline: 'Within 10 days after visit',
      contact_preference: 'blue_whale',
      status: 'Sent to Creator',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'proposal-beauty-blogger',
      business_offer_id: 'offer-jeju-beauty',
      creator_application_id: 'creator-jeju-blogger',
      title: 'Beauty studio review visit',
      provide_details: 'One skincare service with appointment time to be discussed.',
      proposal_message: 'Blue Whale can coordinate a weekday visit that works with your Jeju review route.',
      contact_preference: 'direct_ok',
      status: 'Under Blue Whale Review',
      created_at: now,
      updated_at: now,
    },
  ],
}
